#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${PROJECT_ID:-$(gcloud config get-value project 2>/dev/null || true)}"
REGION="${REGION:-us-central1}"
SERVICE_NAME="${SERVICE_NAME:-softsky-api}"
SERVICE_ACCOUNT_EMAIL="${SERVICE_ACCOUNT_EMAIL:-softsky-api@${PROJECT_ID}.iam.gserviceaccount.com}"

SHARE_BUCKET="${SHARE_BUCKET:-${PROJECT_ID}-softsky-shares}"
SHARE_STORE_DRIVER="${SHARE_STORE_DRIVER:-gcp}"
SHARE_FIRESTORE_COLLECTION="${SHARE_FIRESTORE_COLLECTION:-shares}"
SHARE_GCS_PREFIX="${SHARE_GCS_PREFIX:-shares}"
SHARE_IDEMPOTENCY_COLLECTION="${SHARE_IDEMPOTENCY_COLLECTION:-shareIdempotency}"
SHARE_JOBS_COLLECTION="${SHARE_JOBS_COLLECTION:-shareJobs}"
SHARE_PUBLIC_BASE_URL="${SHARE_PUBLIC_BASE_URL:-}"
SHARE_ALLOWED_ORIGINS="${SHARE_ALLOWED_ORIGINS:-}"
SHARE_RATE_LIMIT_WINDOW_MS="${SHARE_RATE_LIMIT_WINDOW_MS:-60000}"
SHARE_RATE_LIMIT_MAX_MUTATIONS="${SHARE_RATE_LIMIT_MAX_MUTATIONS:-120}"

SHARE_JOBS_ENABLED="${SHARE_JOBS_ENABLED:-true}"
SHARE_JOBS_INLINE_FALLBACK="${SHARE_JOBS_INLINE_FALLBACK:-false}"
SHARE_WORKER_TOKEN="${SHARE_WORKER_TOKEN:-}"
SHARE_TASKS_PROJECT_ID="${SHARE_TASKS_PROJECT_ID:-${PROJECT_ID}}"
SHARE_TASKS_LOCATION="${SHARE_TASKS_LOCATION:-${REGION}}"
SHARE_TASKS_QUEUE="${SHARE_TASKS_QUEUE:-softsky-generation}"
SHARE_TASKS_WORKER_URL="${SHARE_TASKS_WORKER_URL:-}"
SHARE_TASKS_SERVICE_ACCOUNT="${SHARE_TASKS_SERVICE_ACCOUNT:-${SERVICE_ACCOUNT_EMAIL}}"
SHARE_TASKS_AUDIENCE="${SHARE_TASKS_AUDIENCE:-}"

SECURE_COOKIES="${SECURE_COOKIES:-true}"
AUTH_ENABLED="${AUTH_ENABLED:-true}"
AUTH_COOKIE_DOMAIN="${AUTH_COOKIE_DOMAIN:-}"
AUTH_SESSION_COOKIE_NAME="${AUTH_SESSION_COOKIE_NAME:-softsky_session}"
AUTH_OAUTH_STATE_COOKIE_NAME="${AUTH_OAUTH_STATE_COOKIE_NAME:-softsky_oauth_state}"
AUTH_SESSION_TTL_SECONDS="${AUTH_SESSION_TTL_SECONDS:-1209600}"
GOOGLE_OAUTH_CLIENT_ID="${GOOGLE_OAUTH_CLIENT_ID:-}"
GOOGLE_OAUTH_REDIRECT_URI="${GOOGLE_OAUTH_REDIRECT_URI:-}"

GENERATION_ANON_LIMIT="${GENERATION_ANON_LIMIT:-3}"
GENERATION_FIRESTORE_COLLECTION="${GENERATION_FIRESTORE_COLLECTION:-generations}"
GENERATION_GCS_PREFIX="${GENERATION_GCS_PREFIX:-generations}"

GEMINI_MODEL="${GEMINI_MODEL:-gemini-3-flash-preview}"
GEMINI_FALLBACK_MODELS="${GEMINI_FALLBACK_MODELS:-}"
GEMINI_MAX_OUTPUT_TOKENS="${GEMINI_MAX_OUTPUT_TOKENS:-8192}"

GEMINI_API_KEY_SECRET="${GEMINI_API_KEY_SECRET:-softsky-gemini-api-key}"
AUTH_SESSION_SECRET_SECRET="${AUTH_SESSION_SECRET_SECRET:-softsky-auth-session-secret}"
GOOGLE_OAUTH_CLIENT_SECRET_SECRET="${GOOGLE_OAUTH_CLIENT_SECRET_SECRET:-softsky-google-oauth-client-secret}"

MAX_INSTANCES="${MAX_INSTANCES:-200}"
MIN_INSTANCES="${MIN_INSTANCES:-0}"
CONCURRENCY="${CONCURRENCY:-80}"
TIMEOUT="${TIMEOUT:-120s}"
MEMORY="${MEMORY:-512Mi}"
CPU="${CPU:-1}"

if [[ -z "${PROJECT_ID}" ]]; then
  echo "PROJECT_ID is required (or set an active gcloud project)." >&2
  exit 1
fi

if [[ "${AUTH_ENABLED}" == "true" ]]; then
  if [[ -z "${GOOGLE_OAUTH_CLIENT_ID}" || -z "${GOOGLE_OAUTH_REDIRECT_URI}" ]]; then
    echo "GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_REDIRECT_URI are required when AUTH_ENABLED=true." >&2
    exit 1
  fi
fi

echo "Deploying ${SERVICE_NAME} to ${PROJECT_ID}/${REGION}"

ENV_VARS=(
  "SHARE_STORE_DRIVER=${SHARE_STORE_DRIVER}"
  "SHARE_GCS_BUCKET=${SHARE_BUCKET}"
  "SHARE_FIRESTORE_COLLECTION=${SHARE_FIRESTORE_COLLECTION}"
  "SHARE_GCS_PREFIX=${SHARE_GCS_PREFIX}"
  "SHARE_IDEMPOTENCY_COLLECTION=${SHARE_IDEMPOTENCY_COLLECTION}"
  "SHARE_JOBS_COLLECTION=${SHARE_JOBS_COLLECTION}"
  "SHARE_RATE_LIMIT_WINDOW_MS=${SHARE_RATE_LIMIT_WINDOW_MS}"
  "SHARE_RATE_LIMIT_MAX_MUTATIONS=${SHARE_RATE_LIMIT_MAX_MUTATIONS}"
  "SHARE_JOBS_ENABLED=${SHARE_JOBS_ENABLED}"
  "SHARE_JOBS_INLINE_FALLBACK=${SHARE_JOBS_INLINE_FALLBACK}"
  "SHARE_TASKS_PROJECT_ID=${SHARE_TASKS_PROJECT_ID}"
  "SHARE_TASKS_LOCATION=${SHARE_TASKS_LOCATION}"
  "SHARE_TASKS_QUEUE=${SHARE_TASKS_QUEUE}"
  "SHARE_TASKS_SERVICE_ACCOUNT=${SHARE_TASKS_SERVICE_ACCOUNT}"
  "SECURE_COOKIES=${SECURE_COOKIES}"
  "AUTH_ENABLED=${AUTH_ENABLED}"
  "AUTH_COOKIE_DOMAIN=${AUTH_COOKIE_DOMAIN}"
  "AUTH_SESSION_COOKIE_NAME=${AUTH_SESSION_COOKIE_NAME}"
  "AUTH_OAUTH_STATE_COOKIE_NAME=${AUTH_OAUTH_STATE_COOKIE_NAME}"
  "AUTH_SESSION_TTL_SECONDS=${AUTH_SESSION_TTL_SECONDS}"
  "GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}"
  "GOOGLE_OAUTH_REDIRECT_URI=${GOOGLE_OAUTH_REDIRECT_URI}"
  "GENERATION_ANON_LIMIT=${GENERATION_ANON_LIMIT}"
  "GENERATION_FIRESTORE_COLLECTION=${GENERATION_FIRESTORE_COLLECTION}"
  "GENERATION_GCS_PREFIX=${GENERATION_GCS_PREFIX}"
  "GEMINI_MODEL=${GEMINI_MODEL}"
  "GEMINI_FALLBACK_MODELS=${GEMINI_FALLBACK_MODELS}"
  "GEMINI_MAX_OUTPUT_TOKENS=${GEMINI_MAX_OUTPUT_TOKENS}"
)

if [[ -n "${SHARE_PUBLIC_BASE_URL}" ]]; then
  ENV_VARS+=("SHARE_PUBLIC_BASE_URL=${SHARE_PUBLIC_BASE_URL}")
fi

if [[ -n "${SHARE_ALLOWED_ORIGINS}" ]]; then
  ENV_VARS+=("SHARE_ALLOWED_ORIGINS=${SHARE_ALLOWED_ORIGINS}")
fi

if [[ -n "${SHARE_WORKER_TOKEN}" ]]; then
  ENV_VARS+=("SHARE_WORKER_TOKEN=${SHARE_WORKER_TOKEN}")
fi

if [[ -n "${SHARE_TASKS_WORKER_URL}" ]]; then
  ENV_VARS+=("SHARE_TASKS_WORKER_URL=${SHARE_TASKS_WORKER_URL}")
fi

if [[ -n "${SHARE_TASKS_AUDIENCE}" ]]; then
  ENV_VARS+=("SHARE_TASKS_AUDIENCE=${SHARE_TASKS_AUDIENCE}")
fi

ENV_VARS_JOINED="$(IFS='|' ; echo "${ENV_VARS[*]}")"
SECRET_VARS=(
  "GEMINI_API_KEY=${GEMINI_API_KEY_SECRET}:latest"
  "AUTH_SESSION_SECRET=${AUTH_SESSION_SECRET_SECRET}:latest"
  "GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET_SECRET}:latest"
)
SECRET_VARS_JOINED="$(IFS=, ; echo "${SECRET_VARS[*]}")"

DEPLOY_ARGS=(
  run deploy "${SERVICE_NAME}"
  --source backend
  --project "${PROJECT_ID}"
  --region "${REGION}"
  --allow-unauthenticated
  --port 8080
  --cpu "${CPU}"
  --memory "${MEMORY}"
  --concurrency "${CONCURRENCY}"
  --timeout "${TIMEOUT}"
  --max-instances "${MAX_INSTANCES}"
  --min-instances "${MIN_INSTANCES}"
  --set-env-vars "^|^${ENV_VARS_JOINED}"
  --set-secrets "${SECRET_VARS_JOINED}"
)

if [[ -n "${SERVICE_ACCOUNT_EMAIL}" ]]; then
  DEPLOY_ARGS+=(--service-account "${SERVICE_ACCOUNT_EMAIL}")
fi

gcloud "${DEPLOY_ARGS[@]}"

SERVICE_URL="$(gcloud run services describe "${SERVICE_NAME}" --project "${PROJECT_ID}" --region "${REGION}" --format='value(status.url)')"
AUTO_WORKER_URL="${SERVICE_URL}/api/v1/internal/jobs/process"

if [[ -z "${SHARE_TASKS_WORKER_URL}" ]]; then
  gcloud run services update "${SERVICE_NAME}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --update-env-vars "SHARE_TASKS_WORKER_URL=${AUTO_WORKER_URL}" >/dev/null
  SHARE_TASKS_WORKER_URL="${AUTO_WORKER_URL}"
fi

echo "Deployment complete for service: ${SERVICE_NAME}"
echo "Service URL: ${SERVICE_URL}"
echo "Worker URL: ${SHARE_TASKS_WORKER_URL}"
